brew "chezmoi"
brew "fd"
brew "fzf"
brew "git"
brew "go"
brew "jq"
brew "lazygit"
brew "mas"
brew "mosh"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "tree"
brew "watch"
brew "wget"
brew "zsh-autosuggestions"
brew "speedtest-cli"
brew "helix"
brew "eza"
brew "rtk"
brew "git-delta"
brew "marksman"
brew "ltex-ls"
brew "golangci-lint"
brew "rust-analyzer"
brew "zls"

cask "1password"
cask "1password-cli"
cask "adguard"
cask "claude-code"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "rectangle"
cask "tailscale-app"

mas "TextSniper", id: 1528890965
