set guioptions=Ace
set number


highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd VimEnter * wincmd p

autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/

set lines=50
set columns=120

set guifont=Hack:h15
set linespace=2

set fuoptions=maxvert,maxhorz

let g:jellybeans_use_gui_italics = 0
let g:jellybeans_overrides = { 'SignColumn': { 'guibg': '151515' } }
let g:jellybeans_background_color = '151515'
colorscheme jellybeans
