set guioptions=Ace
set number
set equalalways

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd VimEnter * wincmd p

autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/

set lines=50
set columns=120

set fuoptions=maxvert,maxhorz

let g:jellybeans_use_gui_italics = 0
let g:jellybeans_overrides = { 'SignColumn': { 'guibg': '151515' } }
let g:jellybeans_background_color = '151515'
"colorscheme jellybeans
colorscheme base16-harmonic-dark

set guifont=Hack:h11

map <A-Left> <C-T>
map <A-Right> <C-]>

" Navigate tabs with Cmd-[0-9]
map <D-1> 1gt  
map <D-2> 2gt  
map <D-3> 3gt
map <D-4> 4gt
map <D-5> 5gt
map <D-6> 6gt
map <D-7> 7gt
map <D-8> 8gt
map <D-9> 9gt

